// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqOqLT3NJGCH4lkMT9qk0cd9Th5HBDDL4',
    appId: '1:47321429829:web:09f89f5ef86176c211b02c',
    messagingSenderId: '47321429829',
    projectId: 'homy-school',
    authDomain: 'homy-school.firebaseapp.com',
    storageBucket: 'homy-school.appspot.com',
    measurementId: 'G-RWXPD1FRSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAnDhPrEqRwh79hefwZ-ZZpiBNEWVddL4',
    appId: '1:47321429829:android:a48c5b482efbac1711b02c',
    messagingSenderId: '47321429829',
    projectId: 'homy-school',
    storageBucket: 'homy-school.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVIq6wJd4nlxQusUk26BTGjMChGAmpTYA',
    appId: '1:47321429829:ios:e6bc925ea7b0af9e11b02c',
    messagingSenderId: '47321429829',
    projectId: 'homy-school',
    storageBucket: 'homy-school.appspot.com',
    iosClientId: '47321429829-fblr253k6s6k8m8bgb2vvng7i0g51cfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.homySchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVIq6wJd4nlxQusUk26BTGjMChGAmpTYA',
    appId: '1:47321429829:ios:e6bc925ea7b0af9e11b02c',
    messagingSenderId: '47321429829',
    projectId: 'homy-school',
    storageBucket: 'homy-school.appspot.com',
    iosClientId: '47321429829-fblr253k6s6k8m8bgb2vvng7i0g51cfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.homySchool',
  );
}
